// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/orderbook.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for placing a trade
type TradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tradetype     string                 `protobuf:"bytes,1,opt,name=tradetype,proto3" json:"tradetype,omitempty"` // GTILLCANCEL or FILLANDKILL
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`           // BUY or SELL
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`        // Price
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`  // Quantity
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`           // Book name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeRequest) Reset() {
	*x = TradeRequest{}
	mi := &file_proto_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRequest) ProtoMessage() {}

func (x *TradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRequest.ProtoReflect.Descriptor instead.
func (*TradeRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *TradeRequest) GetTradetype() string {
	if x != nil {
		return x.Tradetype
	}
	return ""
}

func (x *TradeRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *TradeRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for canceling an order
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orderid       uint64                 `protobuf:"varint,1,opt,name=orderid,proto3" json:"orderid,omitempty"` // Order ID to cancel
	Book          string                 `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`        // Book name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *CancelRequest) GetOrderid() uint64 {
	if x != nil {
		return x.Orderid
	}
	return 0
}

func (x *CancelRequest) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

// Request message for status check
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_orderbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderbook_proto_rawDescGZIP(), []int{2}
}

// Generic response for Trade and Cancel operations
type TradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`          // Assigned order ID
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP-like status code
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                // Response body from C++ engine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeResponse) Reset() {
	*x = TradeResponse{}
	mi := &file_proto_orderbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponse) ProtoMessage() {}

func (x *TradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponse.ProtoReflect.Descriptor instead.
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *TradeResponse) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *TradeResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TradeResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP-like status code
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                                // Response body from C++ engine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_orderbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *CancelResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CancelResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Response for status check
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP-like status code
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                                // Full orderbook state as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_orderbook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderbook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *StatusResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_proto_orderbook_proto protoreflect.FileDescriptor

const file_proto_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x15proto/orderbook.proto\x12\torderbook\"\x86\x01\n" +
	"\fTradeRequest\x12\x1c\n" +
	"\ttradetype\x18\x01 \x01(\tR\ttradetype\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"=\n" +
	"\rCancelRequest\x12\x18\n" +
	"\aorderid\x18\x01 \x01(\x04R\aorderid\x12\x12\n" +
	"\x04book\x18\x02 \x01(\tR\x04book\"\x0f\n" +
	"\rStatusRequest\"_\n" +
	"\rTradeResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"E\n" +
	"\x0eCancelResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"E\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body2\xc8\x01\n" +
	"\fOrderService\x12:\n" +
	"\x05Trade\x12\x17.orderbook.TradeRequest\x1a\x18.orderbook.TradeResponse\x12=\n" +
	"\x06Cancel\x12\x18.orderbook.CancelRequest\x1a\x19.orderbook.CancelResponse\x12=\n" +
	"\x06Status\x12\x18.orderbook.StatusRequest\x1a\x19.orderbook.StatusResponseB,Z*github.com/TanishqM1/Orderbook/internal/pbb\x06proto3"

var (
	file_proto_orderbook_proto_rawDescOnce sync.Once
	file_proto_orderbook_proto_rawDescData []byte
)

func file_proto_orderbook_proto_rawDescGZIP() []byte {
	file_proto_orderbook_proto_rawDescOnce.Do(func() {
		file_proto_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orderbook_proto_rawDesc), len(file_proto_orderbook_proto_rawDesc)))
	})
	return file_proto_orderbook_proto_rawDescData
}

var file_proto_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_orderbook_proto_goTypes = []any{
	(*TradeRequest)(nil),   // 0: orderbook.TradeRequest
	(*CancelRequest)(nil),  // 1: orderbook.CancelRequest
	(*StatusRequest)(nil),  // 2: orderbook.StatusRequest
	(*TradeResponse)(nil),  // 3: orderbook.TradeResponse
	(*CancelResponse)(nil), // 4: orderbook.CancelResponse
	(*StatusResponse)(nil), // 5: orderbook.StatusResponse
}
var file_proto_orderbook_proto_depIdxs = []int32{
	0, // 0: orderbook.OrderService.Trade:input_type -> orderbook.TradeRequest
	1, // 1: orderbook.OrderService.Cancel:input_type -> orderbook.CancelRequest
	2, // 2: orderbook.OrderService.Status:input_type -> orderbook.StatusRequest
	3, // 3: orderbook.OrderService.Trade:output_type -> orderbook.TradeResponse
	4, // 4: orderbook.OrderService.Cancel:output_type -> orderbook.CancelResponse
	5, // 5: orderbook.OrderService.Status:output_type -> orderbook.StatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_orderbook_proto_init() }
func file_proto_orderbook_proto_init() {
	if File_proto_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orderbook_proto_rawDesc), len(file_proto_orderbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orderbook_proto_goTypes,
		DependencyIndexes: file_proto_orderbook_proto_depIdxs,
		MessageInfos:      file_proto_orderbook_proto_msgTypes,
	}.Build()
	File_proto_orderbook_proto = out.File
	file_proto_orderbook_proto_goTypes = nil
	file_proto_orderbook_proto_depIdxs = nil
}
